---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 22, host: 2223}] #port forwarding to guest ssh#
    - ["forwarded_port", {guest: 80, host: 8080}] #port forwarding to web app on guest#
provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-12.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[role_sinatra_app::default]
    attributes:
